# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TF_Question',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.Question')),
                ('correct', models.BooleanField(default=False, help_text="\u041e\u0442\u043c\u0435\u0442\u044c\u0442\u0435, \u0435\u0441\u043b\u0438 \u043e\u0442\u0432\u0435\u0442 \u043d\u0430 \u0432\u043e\u043f\u0440\u043e\u0441 '\u0414\u0430'. \u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0435\u0441\u043b\u0438 \u043e\u0442\u0432\u0435\u0442 '\u041d\u0435\u0442'", verbose_name='\u0412\u0435\u0440\u043d\u043e')),
            ],
            options={
                'ordering': ['category'],
                'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441 \u0441 \u043e\u0442\u0432\u0435\u0442\u043e\u043c \u0414\u0430/\u041d\u0435\u0442',
                'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b \u0441 \u043e\u0442\u0432\u0435\u0442\u043e\u043c \u0414\u0430/\u041d\u0435\u0442',
            },
            bases=('quiz.question',),
        ),
    ]
