# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meterial',
            new_name='Material',
        ),
    ]
