# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20170421_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='pay',
            field=models.BooleanField(default=False, verbose_name='\u041f\u043b\u0430\u0442\u043d\u044b\u0439'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(upload_to='material/files', verbose_name='\u0424\u0430\u0439\u043b\u044b'),
        ),
    ]
