# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20170421_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='pay',
            new_name='on_off',
        ),
    ]
