# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0002_auto_20170529_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
