# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0430',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=300, verbose_name='\u0424\u0418\u041e')),
                ('age', models.IntegerField(verbose_name='\u0412\u043e\u0437\u0440\u0430\u0441\u0442')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('teacher', models.BooleanField(default=False, verbose_name='\u041f\u0440\u0435\u043f\u043e\u0434\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
                ('teach', models.CharField(max_length=1000, verbose_name='\u0417\u0430\u043d\u044f\u0442\u0438\u044f')),
                ('material', models.CharField(max_length=1000, verbose_name='\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u044b')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Country', verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430')),
            ],
            options={
                'verbose_name': '\u041f\u0435\u0440\u0441\u043e\u043d\u0430',
            },
        ),
    ]
