# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20170517_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
    ]
