# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20170702_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '\u0413\u043e\u0440\u043e\u0434'},
        ),
        migrations.AlterModelOptions(
            name='metro',
            options={'verbose_name': '\u041c\u0435\u0442\u0440\u043e'},
        ),
    ]
