# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_auto_20170702_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u0435\u0434\u043c\u0435\u0442',
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='teach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Teach', verbose_name='\u041f\u0440\u0435\u0434\u043c\u0435\u0442'),
        ),
    ]
