# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_auto_20170702_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='price',
            field=models.IntegerField(default='500', verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u0447\u0430\u0441'),
        ),
    ]
