# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_person_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(default='1', upload_to='avatars', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440'),
        ),
        migrations.AddField(
            model_name='person',
            name='programm',
            field=models.CharField(default='\u0428\u043a\u043e\u043b\u044c\u043d\u0430\u044f', max_length=300, verbose_name='\u041f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0430'),
        ),
    ]
