# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_auto_20170703_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(upload_to='avatars', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440'),
        ),
    ]
