# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_auto_20170703_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='goto_student',
            field=models.BooleanField(default=False, verbose_name='\u0412\u044b\u0435\u0437\u0434 \u0443 \u0443\u0447\u0435\u043d\u0438\u043a\u0443'),
        ),
    ]
